# Copyright 2026 L&A Risk Management Systems (Pty) Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# syntax=docker/dockerfile:1
ARG PHP_VERSION
FROM dunglas/frankenphp:php${PHP_VERSION}-bookworm

USER root

ARG USER_HOME=/home/www-data
ARG USER_ID=1000
ARG GROUP_ID=1000

# host.docker.internal only for Windows and Mac.
# Host IP for Linux.
ENV XDEBUG_CLIENT_HOST=host.docker.internal
ENV XDEBUG_MODE=debug,coverage
ENV COMPOSER_HOME=${USER_HOME}/.composer

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

RUN apt-get update && apt-get install -y unzip \
    && install-php-extensions \
        apcu \
        mysqli \
        pdo_mysql \
        redis \
        pdo_sqlite \
        xdebug \
        bcmath \
        gd \
        gmp \
        imagick \
        soap \
        tidy \
        yaml \
        opcache \
        intl \
        zip

COPY php-ini-overrides.ini /usr/local/etc/php/conf.d/99-overrides.ini

ADD --chown=${GROUP_ID}:${GROUP_ID} https://cs.symfony.com/download/php-cs-fixer-v3.phar /usr/local/bin/php-cs-fixer

RUN cp ${PHP_INI_DIR}/php.ini-development ${PHP_INI_DIR}/php.ini  \
    && chmod a+x /usr/local/bin/php-cs-fixer \
    && groupmod -g ${GROUP_ID} -o www-data \
    && usermod -d ${USER_HOME} www-data \
    && usermod -u ${USER_ID} -g ${GROUP_ID} -o www-data \
    && mkdir -p ${USER_HOME} /config/caddy /data/caddy \
    && touch /var/log/xdebug.log \
    && chown -R www-data:www-data /run /var/tmp ${USER_HOME} /config /data \
    && chown www-data:www-data /var/log/xdebug.log

USER www-data

VOLUME /config/caddy
VOLUME /data/caddy
